### ISSUE TITLE
Refresh of auth tokens

### ISSUE THREAD

**Issue by pinnprophead** [google/google-api-javascript-client#203]
In the documentation, it says that this sample demonstrates the refresh of auth tokens, but I don't see how it does. Can you please explain?

**Comment by michal-husak** [comment]
In the [docs](https://developers.google.com/api-client-library/javascript/help/faq#how-do-i-refresh-the-auth-token-and-how-often-should-i-do--------it) stands:
> Refresh the token by calling gapi.auth.authorize with the client ID, the scope and immediate:true as  parameters.
>
> Currently, the auth token expires after one hour. A common practice is to refresh the auth token after 45 minutes. If you refresh the auth token too often (every five minutes, for example) you will run into the refresh rate limit. (The rate limit is per-user, so the number of user connections is not an issue.)
> 
> The auth token's expires_in field will tell you the token's time to expiration.
> 
> The authSample.html file contains good examples of code that handles auth and token refreshes.

So I have found in [authSample.html](https://github.com/google/google-api-javascript-client/blob/master/samples/authSample.html) on the line 51:

```javascript
// Use a button to handle authentication the first time.
function handleClientLoad() {
    gapi.client.setApiKey(apiKey);
    window.setTimeout(checkAuth,1);
}

function checkAuth() {
    gapi.auth.authorize({client_id: clientId, scope: scopes, immediate: true}, handleAuthResult);
}
```

The call `window.setTimeout(checkAuth,1);` IMHO should be `window.setInterval(checkAuth, 45*60*1000);` because `setTimeout()` fires `checkout()` only once.

**Comment by TMSCH** [comment]
Thanks @michal-husak for your solution. As `gapi.auth` is now deprecated, we recommend moving to `gapi.auth2` that handles automatic token refresh. Doc: https://developers.google.com/identity/sign-in/web/. Closing this issue as a solution has been provided and migrating to GSI v2 fixes the issue.
