### ISSUE TITLE
gapi.auth.authorize silently doesn't work on Electron

### ISSUE THREAD

**Issue by dfournier** [google/google-api-javascript-client#222]
Hi!

gapi.auth.authorize works well on Chrome but doesn't work with Electron. When I add event listener on `windows` for event `message`, Chrome receive a message when the popup close itself, but with Electron nothing is received.

Do you have any idea to make it work with Electron? Should I monkeypatch something?

Best,
David

**Comment by bsittler** [comment]
I am not familiar with Electron (you refer to http://electron.atom.io/ I presume?) and it's not a supported browser or something I can test.

That said, I know some attempts at embedding web-derived apps in non-web packaging have run into problems when they try to use pop-up windows due to an incomplete implementation of the modern web (e.g. DOM/HTML/HDTML/AJAX/HTML5/etc.).

For this specific case, script-opened popup windows (including the authorization pop-up) need to have an "opener" property which is a reference to the window that opened them and allow traversal of the opener's frame hierarchy by code running inside the pop-up, including full script-to-script interaction (function calls, scheduling timeouts, etc.) between the pop-up and an IFRAME with which the pop-up is same-origin.

That's currently required by the gapi.auth.authorize implementation and works in all the supported web browsers but it wouldn't surprise me to discover it doesn't work in an app shell environment which is merely browser-like.

**Comment by bsittler** [comment]
Also, only https web origins (and http, but that's not something I can recommend) are expected to work. What URI scheme does the client app page use?

**Comment by cowsrule** [comment]
We use gapi.auth.authorize in Electron using the following:

```
mainWindow.webContents.on('new-window', handleNewWindow);

...

function handleNewWindow(e, url, frameName, disposition, options)
{
    // Catch OAuth opening a new window and attach callbacks to close it and redirect the main
    // window after it has logged in

    if (url.indexOf('https://accounts.google.com') === 0)
    {
        options.titleBarStyle = 'default';
        var authWindow = new BrowserWindow(options);

        authWindow.webContents.on('did-navigate', function (e, navURL)
        {
            if (navURL.indexOf(appDomain) === 0)
            {
                setTimeout(function ()
                {
                    authWindow.close();

                    mainWindow.loadURL(appURL + '&login=true');
                }, 0);
            }
        });

        authWindow.loadURL(url);

        e.preventDefault();
    }
}
```

**Comment by dfournier** [comment]
Nice @cowsrule ! I'll try your solution 😄

**Comment by TMSCH** [comment]
Hi @dfournier have you been able to resolve your issue?

**Comment by dfournier** [comment]
Yes, by using a classic OAuth authentification with our server. It's much more a workaround than a real solution.

If I remember well, at the time of the issue, the problem was the children window cannot access parent frames. Maybe Electron solved the problem in the meanwhile...

**Comment by TMSCH** [comment]
Thanks for the update @dfournier. As Electron is not a supported environment, server-side authentication is a way to go for now. We'll have to investigate whether we can support such environment. Closing the bug for now, I'll reopen a new one if we plan on supporting it with the newest library, `gapi.auth2`. Thanks!

**Comment by johannesjo** [comment]
Any news on this?

**Comment by TMSCH** [comment]
@johannesjo we're still not planning to support Electron. [AppAuth-JS](https://github.com/openid/AppAuth-JS) might provide a solution for such environment.

**Comment by jhkcia** [comment]
Fixed the issue by setting BrowserWindow.webPreferences.nativeWindowOpen property to true.
