### ISSUE TITLE
Gapi: attempts to signIn/signOut lead to "TypeError: cannot read property 'postMessage' of null"

### ISSUE THREAD

**Issue by Eljoy** [google/google-api-javascript-client#238]
After using ui-router's $state.reload() to update current state, any attempts to GoogleAuth.signIn/GoogleAuth.signOut lead to 
"TypeError: Cannot read property 'postMessage' of null at NU"

**Comment by devravi** [comment]
Facing same issue when calling  .signOut ()  and calling gapi.auth2.getAuthInstance().currentUser.get().reloadAuthResponse();

**Comment by TMSCH** [comment]
@Eljoy @devravi `gapi.auth2` relies on an IFrame to sign in and sign out users. If your application recreates the entire content within `<body>` tags, the IFrame can be removed and this would happen.
Could you confirm this is not the case? You could inspect the content of `<body>` after reloading the state. Otherwise, please provide a minimal snippet of code to reproduce the issue.

**Comment by TMSCH** [comment]
@Eljoy @devravi could you update this thread with more information? Thanks!

**Comment by Eljoy** [comment]
@TMSCH Here is the simplest code one can use to verify the described issue. Click "Sign Out" button and check out the console, to see an error "Uncaught TypeError: Cannot read property 'postMessage' of null". https://plnkr.co/edit/oFcRee13CynUC7LtPERv?p=preview 

Thanks!

**Comment by TMSCH** [comment]
@Eljoy thanks for providing the snippet! The issue is the one I expected and mentioned in my previous comment. The `ng-app` being on `<body>`, it re-renders the entire content and remove the IFrame used by `gapi.auth2`. If I change to:

```
<body>
  <div  ng-app="app" ui-view></div>
</body>
```

The issue does not happen anymore as the IFrame is preserved. Would that solve your problem?

**Comment by Eljoy** [comment]
@TMSCH Yes, thanks! The solution turned out to be so simple :)

**Comment by TMSCH** [comment]
You're welcome! Glad you got it to work!

**Comment by truonglocbinh** [comment]
@TMSCH I have same problem with error " Cannot read property 'postMessage' of null". I create a page login , when I click login button it will authorize and redirect to home page. But when I logout I redirect to sign in page , but I click login button, it doesn't working . I need refresh page and it work well. So i dont use any clients js such as react or angular js. I use ruby on rails as server . Please help me if you can .Thank so much

**Comment by Arjun99** [comment]
I have the same problem with error "Cannot read property 'postMessage' of null" when i try to signin using gapi.
