### ISSUE TITLE
Publish an NPM package

### ISSUE THREAD

**Issue by caesarsol** [google/google-api-javascript-client#432]
Hi, is this project scheduled to be published as an NPM package?

**Comment by Offirmo** [comment]
definitely. That's the established way to do it.

**Comment by StevenEWright** [comment]
Hey @caesarsol,

Does this help? https://github.com/google/google-api-nodejs-client

`npm install googleapis`

Please let me know if you need more help.

Thanks!

**Comment by zeusttu** [comment]
It is possible to `npm install gapi`. If I am not mistaken, this will install https://github.com/phated/node-gapi, which saw its latest commit in 2012 and is marked on Github by its author as no longer maintained. I think there really needs to be an official package, even if just because otherwise people will mistakenly think this incredibly outdated one is the official one.
On the other hand, it looks like that one is at least suited for non-browser clients running NodeJS. The library as linked to in the samples of this repository (the actual library itself is not even here, only a placeholder Javascript file) is not; it relies heavily on the `window` and `document` variables that are defined by default in a browser. So that would be an issue if publishing to a place mostly aimed at NodeJS devs.

**Comment by zeusttu** [comment]
The library referenced by [StevenEWright](https://github.com/google/google-api-javascript-client/issues/432#issuecomment-400807712) seems to be Google's official API client for NodeJS. It's not a perfect copy of this library; class hierarchies and call signatures differ pretty strongly from this library's. Its documentation is also challenging to figure out, particularly as it lacks examples. On the plus side, it has submodules for specific libraries, which this library does not have. It has the same capabilities as this library (apart from the fact that this library only works in browsers and the Node library also works in Node), is reasonably intuitive and logical to use and works well as far as I can tell. It is probably the closest thing Google will ever make to a Node-compatible and NPM-installable version of this library. The downvotes look undeserved as far as I can tell, and I am curious as to their motivation.

**Comment by grant** [comment]
I've look at this. With the way the client is written, it's impossible to make the client public without a full rewrite. The `gapi/client` uses Google-internal tools in lots of places (probably due to it's age).

At best, I could make an effort to mirror a few read-only files that would have the internal comments stripped.

**Comment by sergentj** [comment]
Hi there,

Closing this out as won't fix, because we do not plan to support an NPM package for gapi in its current form. For posterity:

As Grant stated above we can't easily support a NPM package for gapi because it's designed to be dynamically loaded via its own loading mechanism.

We do have a few other related libraries available via NPM, and if they support your use cases they are likely a better fit:
- [Google's node.js client](https://github.com/googleapis/google-api-nodejs-client) 
- [gRPC-web](https://github.com/grpc/grpc-web) - see [this page](https://googleapis.github.io/HowToRPC.html) for more help using RPC with our APIs
