### ISSUE TITLE
gapi fails to load when use locally (not on a webserver)

### ISSUE THREAD

**Issue by wonderfly** [google/google-api-javascript-client#46]
_From [Matthew.Schott](https://code.google.com/u/Matthew.Schott/) on August 10, 2012 08:49:13_

Load the code in the linked fiddle as a local webpage (ie file:///home/test.html).
Fiddle: http://jsfiddle.net/glitchtechscience/LsAwT/2/ What is the expected output? What do you see instead? I should see two alerts. I do see two on a web server, but when run locally (html5 app), it fails with the message "Unable to post message to file://. Recipient has origin null.". What version of the product are you using? On what operating system? Latest. Chromium 18 on Ubuntu 12.04.

_Original issue: http://code.google.com/p/google-api-javascript-client/issues/detail?id=46_

**Comment by valtih1978** [comment]
> Still can't make requests from file:// origin, its been a year waiting for this enhancement!

I wonder why don't they deny the http:// and https:// also. Enabling anything defeats the security (that is why file:// was enchancendly denied in the first place).

**Comment by tdehaeze** [comment]
Any updates on this issue ? Can't make gapi works on my ionic app...

**Comment by bsittler** [comment]
GAPI is currently only supported for use in web applications.

Support for file://... origins is difficult because browsers typically restrict the web APIs available to those origins, including not allowing these origins to be used or sent in postMessage and also not sending them in CORS requests. In both cases they are typically converted to "null" origins, but null origins don't allow the API server the client library is talking to to identify the calling web app.

In your file are you able to directly access the API in question using CORS? If you try this please follow up to let us know whether it worked in your application.

**Comment by bmwertman** [comment]
Anything new on this? I was able to authenticate my ionic app using the `Drive.authenticate` method [here](https://github.com/Raza-Dar/ionic-google-drive/blob/master/www/js/drive.js). But I get the 403 errors from `gapi.client.drive.files.list();` as well as;

Invalid 'X-Frame-Options' header encountered when loading 'https://docs.google.com/picker?protocol=gadgets&origin=http%3A%2F%2Flocalho…%3Atrue%7D))&rpctoken=e2x1eop3h1rr&rpcService=2qeo0ns6gu13&thirdParty=true': 'ALLOW-FROM http://localhost' is not a recognized directive. The header will be ignored.

and

Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://docs.google.com') does not match the recipient window's origin ('http://localhost').
 

when I run the `Drive.showPicker()` method also [here](https://github.com/Raza-Dar/ionic-google-drive/blob/master/www/js/drive.js).

**Comment by bsittler** [comment]
This IFRAME appears to be part of Google Docs picker API, and you'll need to seek assistance in another forum appropriate to that component - I don't know how it is supposed to work.

Also, is this in Chrome? If so, be aware that X-Frame-Options: ALLOW-FROM is documented as not working in Chrome: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options#Browser_compatibility

**Comment by pabx06** [comment]
same error here can't use on local file 
![image](https://cloud.githubusercontent.com/assets/4013370/25564609/4de38ef4-2db7-11e7-9a3c-c651545c0697.png)

**Comment by bsittler** [comment]
Usage of gapi.client from non-https:, non-http: web origins is not supported. As stated in https://developers.google.com/api-client-library/javascript/start/start-js#supported-environments :
> It only works within HTML documents with a <body> element served using the https (preferred) and http protocols.

**Comment by radenkozec** [comment]
@bsittler I have a same error when testing from localhost:

> Failed to execute ‘postMessage’ on ‘DOMWindow’: The target origin provided (‘https://docs.google.com’) does not match the recipient window’s origin (‘http://localhost:48346’).

Not sure how to solve this?

**Comment by bsittler** [comment]
@radenkozec please start a separate entry in the issue tracker and provide more complete details -- although symptoms may be similar, the API not working on non-`http:`, non-`https:` URLs likely has distinct causes from the behavior you are seeing on an `http:` URL.

**Comment by ravikumarvf** [comment]
Is there any conclusion on this ? about how to make it run locally ?

**Comment by bsittler** [comment]
It should work fine with a local web server using `https:` or `http:` URIs. Other URI schemes are not supported at present.

It cannot work correctly served from a `file:` URI due to lack of consistent and complete cross-browser support for such non-web origins. For instance, `file:` URIs do not have a consistent definition of web origin, do not have access to needed storage, are not accurately represented in cross-origin communications (e.g. CORS, `postMessage`, `Origin:`, `Referer:`), do not have consistently isolated and secure storage ownership or cookies, do not have any consistent cross-browser way to defend themselves from other malicious content downloaded to the same computer, don't have any way to ensure a future instance of the same URI actually represents the same application (even on the same computer) due to e.g. temporary download file naming and varying apparent filesystem layouts per-app (in the case of `WebView` and similar embedded-HTML rendering modes), and in general do not consistently function correctly.

**Comment by mayrop** [comment]
FYI - this seems to now be an issue even in the web.

You can even see the issue in https://developers.google.com/+/web/share/
```Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://accounts.google.com') does not match the recipient window's origin ('https://apis.google.com').```

**Related:**
* https://stackoverflow.com/questions/48624138/google-share-button-provokes-failed-to-execute-postmessage-on-domwindow.
* https://productforums.google.com/forum/#!topic/chrome/G81a8tcSg1w

**Comment by TMSCH** [comment]
@mayrop thanks for the report, not sure what started throwing this error, but it can be ignored.

**Comment by rparadis** [comment]
@mayrop @TMSCH  I'm having a similar problem (`Failed to execute 'postMessage'...`.  I'm using google's "Save to Drive" widget button using simple http protocol server.   I wasted nearly a day trying to determine where this was coming and how to get rid of it.  Although, functional, it doesn't seem right to introduce these messages as an error.  I saw a few examples of other websites using this having same problem as well.

**Comment by boulderwhis** [comment]
so are we saying that the only way to get around this issue is to upload html page to a web service? trying to access the civics API and keep running into this while testing. tried using a jquery method as well but the src link won't attach due to CORs policy

**Comment by sbimochan** [comment]
Any solution to Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://docs.google.com') does not match the recipient window's origin ('http://localhost:3000').

**Comment by yong-asial** [comment]
Hi, does anyone has solution to it?

**Comment by johannesjo** [comment]
I am still struggling with this. Sorry for spamming, but did anybody come up with something?

**Comment by jkreddy123** [comment]
Tried testing a simple cloud API, by running index.html from local machine. Ran into this problem. May be, i will have to build a web app and upload to heroku or somewhere else, to test this ...

Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('file://') does not match the recipient window's origin ('null').

**Comment by muratangin187** [comment]
I am developing an electron application with gapi, after the build executable works on file protocol is there any solution exists for this situation?

**Comment by zaytri** [comment]
So if I want to use the Google APIs from a local HTML file, I'd have to build all the web requests myself instead of using this library? This restriction is so annoying.

**Comment by alvarolorentedev** [comment]
2024 and this is still a thing!
