### ISSUE TITLE
Google Sign-In JavaScript client not working on PWA App

### ISSUE THREAD

**Issue by mbellezi** [google/google-api-javascript-client#473]
Greetings,

Since yesterday when I use the gapi.auth2 to do a Google Sign-in on an installed PWA app on Android, the App opens the browser window to select the user, but it remains blank. 
The same page on the Chrome browser on Android open the user selection as usual. The code is the same, from the same server. The code was not modified in more than 15 days. I presume the problem is some change in the gapi JS client code from Google servers. 
Inspecting the PWA Google Sign-in tab on chrome show the following error:

Uncaught Failed to get parent origin from URL hash!

Anyone has any clue how to solve this?

**Comment by sachinrekhi** [comment]
I also just started experiencing this issue about a day ago in my Electron app. User clicks the Sign-In with Google button within my Electron app (which is just a light-weight wrapper around a website), a pop-up window appears, but the window is blank instead of showing the typical Google login options.

The following error is shown in the console in the pop-up window:

```
Uncaught Failed to get parent origin from URL hash!
4188232449-v2-idpiframe.js:136
```

When I Sign-In with Google directly from our website in Chrome, it works fine. So seems like an issue potentially with an interaction with Electron.

Everything was working fine for months and this issue just started occurring about a day or so ago. So seems like a change might have been made on the Google side.

A few other people have also run into this issue on Stack Overflow in the last day: https://stackoverflow.com/questions/52713993/google-sign-in-api-hang-with-uncaught-error-failed-to-get-parent-origin-from-url?noredirect=1&lq=1

**Comment by frankljbe** [comment]
We're seeing a similar issue in our iOS and Android application which are web view wrappers around a website. When the user clicks the button we trigger native auth. Until Monday at about 11:30 am PST. Now when the user attempts to login they are redirected to a blank screen. We didn't make any code or configuration changes the correspond with the failures.

**Comment by BHSPitMonkey** [comment]
Affecting us too, for the last day or so. It seems like if you click the sign in button **again**, while the blank popup is still open from your last attempt, then it goes through (the popup navigates to the correct URL). But every time I click the sign in button without the popup already open, it just opens the blank popup containing the console error.

**Comment by beaukinstler** [comment]
As it might be easier for me, since I'm dealing with anything in real production, I tried changing the client secrets, resetting the secret.  That didn't change anything for me. I've also updated my domain ownership, as that wasn't done yet.  Still the same problems. My app is now letting me log in, but it's supposed to also register new accounts in the DB when they don't exist, which isn't happening. Again, I suspect that's my fault, but I'll report back if I find otherwise.

**Comment by beaukinstler** [comment]
my issue was related to some users not have a 'name' key come back from google. I'm not sure it has to do with scopes, or if it's even a new thing.  I wonder if the recent Google+ problems sparked something about authorizations to access that key.  I changed my logic to derive a name from the email address instead, and all is well for me.

**Comment by sachinrekhi** [comment]
@grant any chance you could help bring this to the attention of the right folks at Google? This appears to be a regression introduced a few days ago causing Google sign-in to now fail in a variety of settings.

**Comment by grant** [comment]
@bochunz Is there a recent gapi client change causing the above error?

**Comment by BHSPitMonkey** [comment]
It's hard to tell if the offending change is in the gapi client or on the server, but there was definitely a regression this week. It's still happening to me, but it's sporadic.

**Comment by boris-hocde** [comment]
Same issue on the example of https://developers.google.com/identity/sign-in/web/sign-in
Click on "Sign in" white button, in the middle of the page

When the Chrome dev tools is open, the popup is correctly loaded.
No issue when using ux_mode = `redirect` instead of `popup`.

https://drive.google.com/open?id=1Qfv_aziyunwo0T7hi4rIPAl28RDH1-WE

**Comment by potiuper** [comment]
Clicking on the "Sign in" button on the [sign-in developer page](https://developers.google.com/identity/sign-in/web/sign-in) works in Chromium, but not Firefox. Firefox returns the "uncaught exception: Failed to get parent origin from URL hash!" error.

**Comment by mbellezi** [comment]
This is killing our PWA. Google should fix it fast. It is certainly a bug
introduced by then recently. The same app opening inside Chrome works
flawless.

Em dom, 14 de out de 2018 12:20, mike-seekwell <notifications@github.com>
escreveu:

**Comment by mike-seekwell** [comment]
Agreed, I just had to spend all weekend programming a workaround because we have no idea when it will be fixed.

**Comment by sachinrekhi** [comment]
@bochunz Were you able to determine if there was a recent client or server change that is causing this regression in Google login?

**Comment by adamazad** [comment]
I switched from `popup` to `redirect` to overcome this issue. My app relays on the `id_token` for exchanging it with a custom token from server. Surpringly, the `id_token` from redirect doesn't return the fields name and picture.

**Comment by grant** [comment]
I pinged an engineer at Google who made recent changes. I'll update here.

**Comment by mike-seekwell** [comment]
@grant Can they roll the changes back while they figure it out?

**Comment by yzhou88** [comment]
Wow, this bug is killing us!

**Comment by mike-seekwell** [comment]
@grant Any update here? Can they please just roll the change back until they figure out what's wrong.

**Comment by aabuhijleh** [comment]
@sachinrekhi I've managed to get it working on Electron by setting `webPreferences.nativeWindowOpen` to true on the pop-up's parent BrowserWindow.

Now it works as well as it's working on the website using Chrome.

**Comment by mbellezi** [comment]
@sachinrekhi , in my case, I don't think i can use this solution. Anyone knows if there is a similar approach for the native Android PWA launcher?

**Comment by rahulswimmer** [comment]
I have an angular 6 + PWA app that is consuming google login. I have implemented it using [https://www.npmjs.com/package/angular-6-social-login](url).

 I have started facing the same issue where pop goes blank and url is **accounts.google.com/o/oauth2/iframe**. In browser, this works just fine. I noticed that in browser when the google pop up appears, client id is being passed in it and when opened as a PWA, client id is not being passed and hence url for pop is not constructed. That might be one of the reason.

I don't see this as a node package issue. I request Google to resolve this issue at the earliest. 

Also since i am using this package for google login, i cannot change popup to redirecturi. Hence i need a workaround in angular 6. Please suggest if any.
@adamazad can you suggest a workaround in angular 6 using the package i have used?
Thank You!

**Comment by kongguibin** [comment]
The change that caused this issue has been rolled back. Can you guys verify if GSI works on PWA now?

**Comment by grant** [comment]
Hi all,
The gapi team told me that this issue should be fixed, tested on iOS.
Can you please test on your environments and verify the fix?

**Comment by sachinrekhi** [comment]
Awesome! Just verified that Google login once again works again in my Electron app.

**Comment by wima75** [comment]
yes, now it works again. Thank you for fixing that.

**Comment by vivek9716** [comment]
yes, now it is working thanks.

**Comment by kevglass** [comment]
Sadly this appears to be broken again on iOS 13.4.1

**Comment by gordomo** [comment]
Hello there!
I'm working on a PWA, so, I was trying the PWA ios Wrapper (https://github.com/xtools-at/iOS-PWA-Wrapper) 
The problem is that the Wrapped apps launch a popup windows (the google login one, but never finish load), and, the real google login pop up freeze after the user get logged in.(this when the user click on the google login button)


Maybe is related to this issue... can't tell... If anyone hears something please let me know!
Thanks!
