### ISSUE TITLE
popup_blocked_by_browser

### ISSUE THREAD

**Issue by marcobraghim** [google/google-api-javascript-client#488]
When I run the code bellow on the pc it runs pretty well, but when I try to do so on the mobile browser I got 'popup_blocked_by_browser' error. Tryed everything, people say that browser use to block when the call is made async, so I change to append action only with user click, but not working on mobile yet...

```javascript
/* global gapi, swal */

$(function() {
  document.getElementById('btn-google-login').onclick = function() {

    gapi.load('auth2', function() {

      // Retrieve the singleton for the GoogleAuth library and set up the client.
      auth2 = gapi.auth2.init({
        client_id: $('meta[name="google-signin-client_id"]').attr('content'),
        cookiepolicy: 'single_host_origin',
        prompt: 'consent',
        immediate: false
      }, function() {});

      var proccedLogin = function(resp) {
        // my login code
      }

      auth2.signIn()
        .then(proccedLogin)
        .catch(function(error) {
          alert(JSON.stringify(error, undefined, 2))
        })

    }) // end load
  }
})

```

Ps.: I know there's another issue with this error message, but seems to be another question for me

**Comment by nuram07** [comment]
maybe try to disable all the extensions - in my case disabling uBlock Origin helped

**Comment by marcobraghim** [comment]
There isn't even one extension installed =/

**Comment by heyheyjc** [comment]
Because you're loading auth2 during the click, the authorization
    call you're making is by that point no longer in the click event but
    is asynchronous, and regarded by the browser as no longer because of
    user interaction. You need to load and initialize auth2 earlier,
    then make the call synchronously in the click event.
    
    Jake
    
    On 5/21/2019 4:04 AM, Marco A. Braghim
      wrote:
    
    
      
      There isn't even one extension installed =/
      —
        You are receiving this because you are subscribed to this
        thread.
        Reply to this email directly, view it on GitHub, or mute the thread.
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/google/google-api-javascript-client/issues/488?email_source=notifications\u0026email_token=AG4XGOUGV2TRRVFLEMTRPWTPWPJNXA5CNFSM4GKUVT42YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODV3RYLY#issuecomment-494345263",
"url": "https://github.com/google/google-api-javascript-client/issues/488?email_source=notifications\u0026email_token=AG4XGOUGV2TRRVFLEMTRPWTPWPJNXA5CNFSM4GKUVT42YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODV3RYLY#issuecomment-494345263",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
    
    
    -- 
jake@youmescript.com
https://youmescript.com
Forum: https://youmescript.com/forum

**Comment by nuram07** [comment]
Try this simple code below to verify your environment is capable of opening a popup window. 

<button id="myBtn" onclick="myFunction()">Open PopUp</button>
<script>
function myFunction(){
	console.log('clicked')
	window.open('https://javascript.info/')
}
</script>

If that works, please try this code, because it works for me:

import { Injectable, NgZone } from '@angular/core';
import { BehaviorSubject, Observable } from 'rxjs';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { environment } from 'ClientApp/environments/environment';
import { CookieService } from 'ngx-cookie-service';

@Injectable()
export class AuthenticatorService {


    private authInstance: gapi.auth2.GoogleAuth;

    private subject: BehaviorSubject<boolean> = new BehaviorSubject<boolean>(false);
    public aspToken: string;
    public picture: string;

    public isLoggedIn: boolean = false;
    public isAuth2Loaded: boolean = false;

    public getIsLoggedIn(): Observable<boolean> {
        return this.subject.asObservable();
    }

    constructor(private http: HttpClient, private cookieService: CookieService, private zone: NgZone) {
              
        gapi.load('auth2', function () { });      
    }

    public signIn(): void {

        if (this.isLoggedIn)
            return;

        gapi.auth2.init({
            client_id: 'YOUR_CLIENT_ID',
            fetch_basic_profile: true           
        }).then((authInstance) => {
            console.log("gapi init in");
            console.log(authInstance);
            this.authInstance = authInstance;

            authInstance.signIn().then((authUser) => {
                console.log("im auth2 in");
                console.log(authUser);              
            });
        });      
    };

    public signOut(): void {
        
        if (this.authInstance) {
            this.authInstance.signOut().then(() => {
                console.log("im auth2 out");
            }, (err) => {
                console.error(err);
            });
        }
    }
  
    private handleError(error: any) {
        console.error('An error occurred', error);

        return Promise.reject(error);
    }
}
Hope this helps

**Comment by marcobraghim** [comment]
I'm having no time to test it all, sadly :cry:

**Comment by sergentj** [comment]
Sorry we didn't respond sooner. Hopefully the solutions above are helpful. If not, and anyone is still having a problem here, please try posting on [Stack Overflow under the google-oauth tag](https://stackoverflow.com/questions/tagged/google-oauth). Thanks.
