### ISSUE TITLE
gapi.client.init stopped working

### ISSUE THREAD

**Issue by Willdorf** [google/google-api-javascript-client#517]
gapi.client.init was working fine (for months) but has now stopped working with the following error:

{
  "error": {
    "code": 400,
    "message": "Request contains an invalid argument.",
    "status": "INVALID_ARGUMENT",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.BadRequest",
        "fieldViolations": [
          {
            "field": "kind,name,version,rootUrl,servicePath,resources,parameters,methods,batchPath,id",
            "description": "Error expanding 'fields' parameter. Cannot find matching fields for path 'kind'."
          }
        ]
      }
    ]
  }
}

**Comment by daphshez1** [comment]
The reason seems to be that the API Discovery Service for BigQuery is slighty broken. https://issuetracker.google.com/issues/129897211

**Comment by grant** [comment]
This issue looks fixed after looking at the link posted.
If it isn't, please re-open this issue.

**Comment by sychedelix** [comment]
I have the same issue with Google Tag Manager since last Wednesday.

[https://content.googleapis.com/discovery/v1/apis/tagmanager/v2/rest?fields=kind%2Cname%2Cversion%2CrootUrl%2CservicePath%2Cresources%2Cparameters%2Cmethods%2CbatchPath%2Cid&pp=0](https://content.googleapis.com/discovery/v1/apis/tagmanager/v2/rest?fields=kind%2Cname%2Cversion%2CrootUrl%2CservicePath%2Cresources%2Cparameters%2Cmethods%2CbatchPath%2Cid&pp=0)

`"error": {
        "code": 400,
        "message": "Request contains an invalid argument.",
        "status": "INVALID_ARGUMENT",
        "details": [{
                "@type": "type.googleapis.com/google.rpc.BadRequest",
                "fieldViolations": [{
                        "field": "kind,name,version,rootUrl,servicePath,resources,parameters,methods,batchPath,id",
                        "description": "Error expanding 'fields' parameter. Cannot find matching fields for path 'kind'."
                }]
        }]
  }`
