### ISSUE TITLE
The dev document are gone

### ISSUE THREAD

**Issue by jjbully** [google/google-api-javascript-client#537]
The Dev Documents are gone, I cant find it from all the link in readme

**Comment by ianp** [comment]
Presumably this is what the raft of “DevSite Import” tickets (e.g. #534) are referring to. It would be nice if these docs could be added back sooner rather than later, as currently all of the documentation and links are completely broken, across all Google developer sites ☹️

**Comment by grant** [comment]
Hey @jjbully and @ianp, sorry for the hold-up. I've been working on making these docs open source. The content has not been changed from developers.google.com, and the exact contents have been added to this repo.

Since the docs and samples are now open sourced, please make issues and PRs to fix them where they are wrong!
