### ISSUE TITLE
gapi.client.request uses global batch request

### ISSUE THREAD

**Issue by gkiely** [google/google-api-javascript-client#550]
When using `gapi.client.request` as part of a batch request it uses the global batch endpoint.

Example:
```js
const batch = gapi.client.newBatch();
const request = gapi.client.request({
  path: `drive/v3/files?q='id in parents' and trashed = false`
});
batch.add(request);
batch.then();
```

**URL that gets called:** https://content.googleapis.com/batch?key={myKey}
**Expected URL:** https://content.googleapis.com/batch/drive/v3?key={myKey}

**Comment by gkiely** [comment]
Hey @grant just wanted to see if this is feasible. It's related to the global batch endpoint being deprecated. Thanks!

**Comment by dvanderb** [comment]
I realize this is an old issue but the root cause here is that hand crafted(non discovery based) requests always went to global batch.  Now that global batch is no longer supported the appropriate approach is to always use discovery generated requests in batches. I have sent a pull request updating the documentaiton.

#728
