### ISSUE TITLE
How to manually refresh access_token using gapi?

### ISSUE THREAD

**Issue by KonstantinKolodnitsky** [google/google-api-javascript-client#590]
Hi. I'm storing access token and refresh token on the backend. How can I silently update access token on the frontend?. I can easily do that on the backend but couldn't find any examples for the client-side. Looking for the gapi method.
gapi.auth2.authorize will open a new tab to log user in. That's not what we want.

P.S. Yes I'm aware gapi does it "automatically". But not in our case. We use server-side SSO for now. I'm trying to use gapi for one small feature for now.

Thank you

**Comment by grant** [comment]
Hi. I'm not sure if this faq question helps:
https://github.com/google/google-api-javascript-client/blob/master/docs/faq.md#how-do-i-refresh-the-auth-token-and-how-often-should-i-do-it

Did you use `immediate:true`?

Otherwise, you might need to manually refresh:

```
POST /token HTTP/1.1
Host: oauth2.googleapis.com
Content-Type: application/x-www-form-urlencoded

client_id=your_client_id&
client_secret=your_client_secret&
refresh_token=refresh_token&
grant_type=refresh_token
```

See the docs:
https://developers.google.com/identity/protocols/OAuth2WebServer#offline

I'm not sure if there is a helper method for this.
