### ISSUE TITLE
Viewing/downloading file contents (via alt='media') does not work any more

### ISSUE THREAD

**Issue by johannesjo** [google/google-api-javascript-client#600]
I was previously able to get the file contents to process directly in JavaScript via the following request:
```
{
      method: 'GET',
      url: `https://content.googleapis.com/drive/v3/files/${encodeURIComponent(fileId)}`,
      params: {
        source: 'downloadUrl',
        alt: 'media',
      },
      responseType: 'text'
}
```
This stopped working without me changing anything. After a redirect (307) to a very long url (`
https://XXX-apidata.googleusercontent.com/download/drive/v3/files/{FILE_ID}?qk=XXX`) a 405 is thrown.

Did you deactivate this feature?

**Comment by leolimar** [comment]
When did it stop working? Do you believe it may be related to the following change:  Starting on January 1, 2020, the Google Drive API will no longer support downloads that authenticate using the “access_token” query parameter. This change will only affect download calls to the files.get, revisions.get and files.export endpoints. After this date, download calls to these endpoints that authenticate using the query parameter will fail, unless you change the authentication method. Drive API calls to these endpoints that do not download media content will not be affected. We recommend that you migrate your requests to authenticate using an HTTP header. However, if this is not possible due to browser restrictions, you may want to use cookie authentication instead.

**Comment by johannesjo** [comment]
Thanks for getting back to me! I can't pinpoint the exact point of time, but I am sure that it at least worked until the 18th of January. There have been no changes to my code. Can't really say if the redirect occurred before it stopped working or not.

**Comment by johannesjo** [comment]
I just recognized that there is another error shown in the console for the `https://XXX-apidata.googleusercontent.com/download/drive/v3/files/{FILE_ID}?qk=XXX` OPTIONS request:
```
CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

**Comment by johannesjo** [comment]
Could someone confirm whether this is a bug or intended to be like this?

**Comment by johannesjo** [comment]
https://github.com/localForage/localForage/issues/788
