### ISSUE TITLE
Internal People Api Permission Denied

### ISSUE THREAD

**Issue by leehen** [google/google-api-javascript-client#608]
We have a google extension for GSuite.
We use 
gapi.load('auth2', ()=>{
  gapi.auth2.init({client_id, scope, response_type}).then(
  ....
  )
})
to get signed in user's info and access token with given api permissions, however, there is one API permission that we cannot find a scope for it: "Internal People API". When we typing in the recipient box in gmail or "Share with others" in docs, we get 403 from "people-pa.clients6.google.com" stating that we don't have permission for "Internal People API" and asking us to enable it in console.developers.google.com. We cannot find such api to enable and we cannot find any scope to add to "gapi.auth2.init". We enabled People API but I think it is different api.

Any idea which scope should we add to our project for this "Internal People API"?

Much appreciated!

**Comment by ccdunder** [comment]
Thanks for reaching out. This tracker is for Google API Javascript client bugs. It looks like this issue is due to server permissions with the API you are trying to call. I recommend reaching out to the maintainers of the API regarding this issue. I'm closing this for now with the understanding that this isn't an issue with the Javascript client.
