### ISSUE TITLE
Batch: requests are no longer part of a single request

### ISSUE THREAD

**Issue by gkiely** [google/google-api-javascript-client#650]
Hi guys, from what I can see the following code will trigger 3 network calls instead of 1. 

```js
const batch = gapi.client.newBatch();
batch.add(gapi.client.request({path: 'drive/v3/files/' + id});
batch.add(gapi.client.request({path: 'drive/v3/files/' + id});
batch.add(gapi.client.request({path: 'drive/v3/files/' + id});
batch.then((res) => {
  console.log(res.result);
})
```

This is for a homogenous batch request. 
It wasn't always the case so I wanted to see what might have changed and if it's related to this [blog post](https://developers.googleblog.com/2018/03/discontinuing-support-for-json-rpc-and.html)

Thanks!

**Comment by dvanderb** [comment]
The change in behavior is related to the blog post you linked.

While your example is a homogenous batch request it is not sent to an API specific batch endpoint since the requests are hand crafted.  A change was recently made to the javascript client which results in the behavior you are experiencing in order to avoid application errors for users once the global batch endpoints are disabled.

In order for batches to work properly you should migrate to using the generated API to create requests as in this example: https://developers.google.com/drive/api/v3/quickstart/js .  Requests like `gapi.client.drive.files.get({fileId: id})` can be added to a batch and will be sent as a single network call.

**Comment by gkiely** [comment]
Thanks @dvanderb that was the issue.
