### ISSUE TITLE
Which is the "canonical" js API CDN URL?

### ISSUE THREAD

**Issue by coolaj86** [google/google-api-javascript-client#694]
This page <https://developers.google.com/identity/protocols/oauth2/javascript-implicit-flow> says to use this:
 - https://apis.google.com/js/api.js

This adjacent page <https://developers.google.com/identity/sign-in/web/sign-in> says to use this:
- https://apis.google.com/js/platform.js

Yet another page <https://developers.google.com/identity/sign-in/web/build-button> says to use this:
- https://apis.google.com/js/api:client.js

All of them seem to be `gapi`. Are they any different? Which is the "real" one? Which one should actually be used?

Is there a way to preload a particular set of necessary features so that the async load times (ex `gapi.load('auth2')`) aren't so slow?

**Comment by Li357** [comment]
Did you ever figure this out?

**Comment by coolaj86** [comment]
Bump. Which JS API CDN should we be using in 2021? Or are they just legacy aliases that point to the same thing?

**Comment by dvanderb** [comment]
Unfortunately this is a nuanced question and it depends on what you are trying to achieve. The two primary cases are:

GAPI loader(api.js, api:client.js, etc..): You want to load GAPI and be able to execute gapi.load(..). The difference between api.js and api:client.js is the latter will automatically execute a gapi.load('client', ...) for you but this does *not* preload it.  Similarly you could do "api:auth2.js". Really this just avoids you typing out gapi.load(..) in your load callback.
GAPI platform.js: You want to use the "widget" platform which enables the automatic div rendering with the <div class="g-..."> element which is in the base web/sign-in documentation.

The reason why the different sign-in pages say different things is just the desired effect. In the latter case(customizing the button) loading platform.js will end up with the client loading extra code that it does not need since you are not doing the automatic rendering from the div tag.

Hopefully that helps.

**Comment by coolaj86** [comment]
@dvanderb Thanks for the details! This is great information. Is there a list of the various javascript files so that I could go ahead and put the ones I know I'm going to need in a script tag and avoid the extra latency?
