### ISSUE TITLE
Why does gapi.client.init load iFrame and resources from content.googleapis.com instead of specific subdomains

### ISSUE THREAD

**Issue by etyp** [google/google-api-javascript-client#750]
Not sure where else to put this, so please let me know if there's a better channel to ask this question.

It seems like calling `gapi.client.init` will always load a resource and iFrame from `content.googleapis.com`.

We have a partner who we're building an integration with; the integration is tightly scoped to using the Calendar API. The partner has concerns over having `content.googleapis.com` in a domain allow list because it is very broad. The iFrame / proxy is coming from `content.googleapis.com`. Ideally, we'd expect a `gapi.client.init` to load libraries from their respective subdomain. For example, if we load the Calendar API like:

```
gapi.client.init({
    discoveryDocs: [
      'https://www.googleapis.com/discovery/v1/apis/calendar/v3/rest',
    ],
  });
```

We would expect the gapi client to load the SDK resource from something like `calendar.googleapis.com` rather than `content.googleapis.com`.

Worst case scenario, we can change our code to make vanilla HTTP calls to the REST API, but it's obviously more ideal to use the out-of-the-box Javascript SDK.

**TLDR: Why does gapi.client.init load an iFrame and resources from content.googleapis.com rather than from specific googleapis.com subdomains based on what's passed into the discovery docs?**

**Comment by dvanderb** [comment]
This is expected behavior for the Calendar API. Some APIs use API specific subdomains but some do not. According to the discovery doc for calendar the rootUrl is "www.googleapis.com" which translates into content.googleapis.com for requests at runtime. It is also important to note that this can change at any point to an API specific subdomain based on a change in the discovery document.
