### ISSUE TITLE
IE11 Google Picker Buttons are not responsive

### ISSUE THREAD

**Issue by mluong888** [google/google-api-javascript-client#772]
On IE11, the google picker's X button, select button and cancel button don't consistently work. From my debugging, the pickerCallback function is not always called after clicking on these buttons, causing my google picker to be unresponsive.

Strangely enough, a temporary workaround seems to be opening the inspect element and switching between tabs. For some reason, switching tabs in the developer tools and then clicking a button seems to work. This is not an intuitive workaround and only works temporarily also...

Could there be some bug regarding the PickerBuilder.setCallback function?

**Comment by sergentj** [comment]
Hi,

I am not sure what the underlying problem is here, but Drive does not officially support IE11, so this is not surprising to see. It is unlikely to get fixed or stay fixed because we no longer test this code against IE11 as a result.

See here for more info:
https://support.google.com/drive/answer/2375082
https://support.google.com/a/answer/33864

Sorry I don't have a better answer for you.
