### ISSUE TITLE
Cannot catch errors on requestAccessToken UI issues or user abort

### ISSUE THREAD

**Issue by ffeldhaus** [google/google-api-javascript-client#816]
When using `requestAccessToken` the UI may not be opened in cases where the request wasn't initialised by a user action and the user hasn't allowed popups exlicitly (which is the default). Also the user can close the UI without finishing the authentication. In both cases it seems that no error is produced and it is not possible to catch and react to these cases.

Please provide a way to catch errors with opening the UI and completing the UI based authentication.

**Comment by dvanderb** [comment]
For authentication/authorization issues please note that gapi.auth2 has been deprecated and replaced with [Google Identity Services](https://developers.googleblog.com/2021/07/launching-our-new-google-identity-services-apis.html). See https://developers.googleblog.com/2021/08/gsi-jsweb-deprecation.html for more information. Since this question is related to authentication/authorization please look at the associated documentation or post questions on [Stack Overflow](https://stackoverflow.com/questions/tagged/google-oauth) with the google-oauth tag.

**Comment by subhamX** [comment]
@dvanderb I am using Google Identity Services, and yet facing similar problems. Have a look at the function below to loginUser and get the access_token:

```js
const loginUser = async () => {
  const tokenResponse = await new Promise<TokenResponse>((resolve, reject) => {
    try {
      // Settle this promise in the response callback for requestAccessToken()
      client.callback = (resp) => {
        if (resp.error !== undefined) {
          reject(resp);
        }
        resolve(resp);
      };
      // requesting access token
      client.requestAccessToken({ prompt: 'consent' });
    } catch (err) {
      console.log(err)
    }
  });
  return tokenResponse;
}
```
Invoking `loginUser()` causes a new pop-up. 
* If the user selects an account, I get the `tokenResponse` (which contains `access_token`). Works great. 🚀
* But if the user closes the `pop-up`, the `Promise` never resolves, since we are waiting for the callback to fire, which never happens. 😥

Is there a way we could find if the user has closed the `pop-up`?

**Comment by ffeldhaus** [comment]
@dvanderb This is not about `gapi.auth2` but about `google.accounts.oauth2`. @subhamX exactly described the issue. In my opinion this is a bug or at least a severe limitation of the google-api-javascript-client library.

I found the following workaround which rejects the promise after a timeout. This is not a nice user experience, as setting the timeout to a few settings will ensure that the Promise is quickly rejected, but if the user is just searching for the password, the authentication flow is interrupted even though it was still active. It would be much better if the library rejects the Promise on user closing the authentication popup or if the popup could not be displayed (e.g. because it was not triggered by a user interaction / button click).

Here is my workaround:
```javascript
// timeout a promise if not resolved or rejected
const timeoutPromise = (promise, timeout) => {
	let timer;
	return Promise.race([
		promise,
		new Promise((_r, rej) => timer = setTimeout(rej, timeout))
	]).finally(() => clearTimeout(timer));
}

const client = (window as any).google.accounts.oauth2.initTokenClient({
  client_id: process.env.GOOGLE_CLIENT_ID,
  scope: `profile email`,
  callback: '' // defined at request time
});

const loginUser = async () => {
  const tokenResponse = await timeoutPromise(
    new Promise<TokenResponse>((resolve, reject) => {
      try {
        // Settle this promise in the response callback for requestAccessToken()
        client.callback = (resp) => {
          if (resp.error !== undefined) {
            reject(resp);
          }
          resolve(resp);
        };
        // requesting access token
        client.requestAccessToken({ prompt: 'consent' });
      } catch (err) {
        console.log(err)
      }
    ,60*1000)
  });
  return tokenResponse;
}
```

**Comment by dvanderb** [comment]
I understand that there is an issue.. the `google.accounts.oauth2.*` functionality is part of the new Google Identity Services library and is supported under the stack overflow tag I posted above.

**Comment by surajgov-quizizz** [comment]
we can pass a function for the params: `error_callback`
```js
const client = (window as any).google.accounts.oauth2.initTokenClient({
  client_id: process.env.GOOGLE_CLIENT_ID,
  scope: `profile email`,
  callback: '' // defined at request time,
  error_callback: (err) => {
    // executed when the auth process encounters an unexpected error (also when user aborts it)
  }
});
```
