### ISSUE TITLE
Where can I get an uncompressed version of https://apis.google.com/js/client.js

### ISSUE THREAD

**Issue by wonderfly** [google/google-api-javascript-client#93]
_From [n...@blossom.io](https://code.google.com/u/107329962638892725242/) on July 19, 2013 09:56:19_

I'm looking for an uncompressed version of client.js, but I couldn't find it in this repository. I only used the browse feature from google code.

_Original issue: http://code.google.com/p/google-api-javascript-client/issues/detail?id=93_

**Comment by zboralski** [comment]
any reasons why?

**Comment by kfogel** [comment]
I'm also curious, echoing @zboralski's question.

It makes it harder to ship open source apps that call Google APIs.  It's a standard (and IMHO good) practice for open source to provide all javascript from the native server, instead of asking clients to load JS from a third-party server such as https://apis.google.com/.  So you can download jquery and whatnot and have it all load from your app's own server... But then you run into the minified Google Javascript files, and it's not even clear what copyright terms they're under (they don't say).  Do you ship it with your own app, risking copyright infringement and risking making your app not fully open source?  

Or do you have your code direct client-side users to download it from Google into their own browsers, thus creating a load-time dependency on https://apis.google.com/'s SLA, and, incidentally, exposing your users to some unknown copyright infringement risk themselves?

I understand that Google is under no obligation to release any of this code under an open source license.  However, I hope Google will do so, because the current situation is rather hostile to open source applications that call Google APIs.
